CREATE DATABASE virtual;

USE virtual;

CREATE TABLE cadfun (
  CODFUN  INTEGER NOT NULL PRIMARY KEY,
  NOME    VARCHAR(40) NOT NULL,
  DEPTO   CHAR( 2),
  FUNCAO  CHAR(20),
  SALARIO DECIMAL(10, 2)
);

SHOW TABLES;

DESCRIBE cadfun;

INSERT INTO cadfun (
  CODFUN, 
  NOME, 
  DEPTO, 
  FUNCAO, 
  SALARIO) 
VALUES (
  12,
  'CARLOS ALBERTO',
  '3',
  'VENDEDOR',
  1530.00
);

INSERT INTO cadfun (
  CODFUN, 
  NOME, 
  DEPTO, 
  FUNCAO, 
  SALARIO) 
VALUES (
  15,
  'MARCOS HENRIQUE',
  '2',
  'GERENTE',
  1985.75
);

INSERT INTO cadfun (
  CODFUN, 
  NOME, 
  DEPTO, 
  FUNCAO, 
  SALARIO) 
VALUES (
  7,
  'APARECIDA SILVA',
  '3',
  'SECRETARIA',
  1200.50
);

INSERT INTO cadfun (
  CODFUN, 
  NOME, 
  DEPTO, 
  FUNCAO, 
  SALARIO) 
VALUES (
  9,
  'SOLANGE PACHECO',
  '5',
  'SUPERVISORA',
  1599.51
);

INSERT INTO cadfun (
  CODFUN, 
  NOME, 
  DEPTO, 
  FUNCAO, 
  SALARIO) 
VALUES (
  6,
  'MARCELO SOUZA',
  '3',
  'ANALISTA',
  2250.11
);

INSERT INTO cadfun (
  CODFUN, 
  NOME, 
  DEPTO, 
  FUNCAO, 
  SALARIO) 
VALUES (
  1,
  'CELIA NASCIMENTO',
  '2',
  'SECRETARIA',
  1200.50
);

INSERT INTO cadfun VALUES (
  2,
  'WILSON DE MACEDO',
  '3',
  'PROGRAMADOR',
  1050.00
);

INSERT INTO cadfun VALUES (
  5,
  'AUGUSTO SOUZA',
  '3',
  'PROGRAMADOR',
  1050.00
);

LOAD DATA LOCAL INFILE "dados.txt" INTO TABLE cadfun;

SELECT * FROM cadfun;

SELECT NOME, FUNCAO FROM cadfun;

SELECT NOME FROM cadfun WHERE DEPTO = '3';

SELECT NOME, SALARIO FROM cadfun ORDER BY NOME;

SELECT NOME, SALARIO FROM cadfun ORDER BY NOME DESC;

SELECT DEPTO, NOME FROM cadfun ORDER BY DEPTO, NOME DESC;

SELECT NOME FROM cadfun WHERE DEPTO = '3' ORDER BY NOME;

SELECT * FROM cadfun WHERE CODFUN = 7;

UPDATE cadfun SET SALARIO = 2300.56 WHERE CODFUN = 7;

SELECT * FROM cadfun WHERE CODFUN = 7;

SELECT * FROM cadfun WHERE NOME = 'ANA BASTOS';
UPDATE cadfun SET DEPTO = '3' WHERE NOME = 'ANA BASTOS';
SELECT * FROM cadfun WHERE NOME = 'ANA BASTOS';

SELECT * FROM cadfun;

UPDATE cadfun SET SALARIO = SALARIO * 1.10;

SELECT * FROM cadfun;

DELETE FROM cadfun WHERE DEPTO = '2';

SELECT * FROM cadfun;

DELETE FROM cadfun WHERE NOME = 'MARCELO SOUZA';

SELECT * FROM cadfun;

ALTER TABLE cadfun ADD ADMISSAO DATE;

SELECT * FROM cadfun; 

UPDATE cadfun SET ADMISSAO = '2006-01-15' WHERE CODFUN = 2;
UPDATE cadfun SET ADMISSAO = '1999-10-21' WHERE CODFUN = 3;
UPDATE cadfun SET ADMISSAO = '2004-10-21' WHERE CODFUN = 4;
UPDATE cadfun SET ADMISSAO = '2006-04-26' WHERE CODFUN = 5;
UPDATE cadfun SET ADMISSAO = '1980-05-10' WHERE CODFUN = 7;
UPDATE cadfun SET ADMISSAO = '1999-12-15' WHERE CODFUN = 9;
UPDATE cadfun SET ADMISSAO = '2000-12-21' WHERE CODFUN = 12;
UPDATE cadfun SET ADMISSAO = '2000-10-21' WHERE CODFUN = 25;

SELECT * FROM cadfun; 

SELECT NOME, ADMISSAO FROM cadfun WHERE MONTH(ADMISSAO) = 12;

SELECT NOME, ADMISSAO FROM cadfun WHERE ADMISSAO >= '2000-01-01';

INSERT INTO cadfun VALUES (
  15,
  'MARCOS HENRIQUE',
  '2',
  'GERENTE',
  2184.33,
  '2006-05-25'
);

INSERT INTO cadfun VALUES (
  20,
  'AUDREY TOLEDO',
  '2',
  'SUPERVISORA',
  1700.00,
  '2006-07-05'
);

INSERT INTO cadfun VALUES (
  22,
  'SANDRA MANZANO',
  '2','ANALISTA',
  2000.00,
  '2006-07-01'
);

INSERT INTO cadfun VALUES (
  24,
  'MARCIO CANUTO',
  '2',
  'PROGRAMADOR',
  1200.00,
  '2006-07-10'
);

SELECT * FROM cadfun;

CREATE TABLE morto (
  CODFUN   INTEGER PRIMARY KEY,
  NOME     VARCHAR(40),
  DEPTO    CHAR( 2),
  FUNCAO   CHAR(20),
  SALARIO  DECIMAL(10, 2),
  ADMISSAO DATE
);

SHOW TABLES;

INSERT INTO morto 
  SELECT CODFUN, NOME, DEPTO, FUNCAO, SALARIO, ADMISSAO 
  FROM cadfun 
  WHERE CODFUN = 12
;

SELECT * FROM morto; 

DELETE FROM cadfun WHERE CODFUN = 12;

SELECT * FROM cadfun;
SELECT * FROM morto;

SELECT NOME FROM cadfun WHERE SALARIO = (SELECT SALARIO FROM morto);

SELECT * FROM cadfun WHERE SALARIO = (SELECT SALARIO FROM morto);

SELECT * FROM cadfun WHERE DEPTO = (SELECT DEPTO FROM morto);

