USE virtual;

SELECT NOME, SALARIO + 100 FROM cadfun;

SELECT NOME, SALARIO FROM cadfun;

SELECT NOME, SALARIO * 1.20 FROM cadfun;

SELECT 2 + 3 * 5;

SELECT (2 + 3) * 5;

SELECT * FROM cadfun WHERE DEPTO = '5';

SELECT * FROM cadfun WHERE FUNCAO = 'VENDEDOR';

SELECT * FROM cadfun WHERE SALARIO <= 1700;

SELECT * FROM cadfun WHERE SALARIO > 1700 + 50;

SELECT * FROM cadfun WHERE (DEPTO = '3') AND (FUNCAO = 'PROGRAMADOR');

SELECT * FROM cadfun WHERE (DEPTO = '3') OR (DEPTO = '5');

SELECT * FROM cadfun WHERE NOT (FUNCAO = 'VENDEDOR');

SELECT * FROM cadfun WHERE (DEPTO = '5') XOR (FUNCAO = 'PROGRMADOR');

ALTER TABLE cadfun ADD FILHOS SMALLINT;
ALTER TABLE morto ADD FILHOS SMALLINT;

SELECT NOME, FILHOS FROM cadfun;

UPDATE cadfun SET FILHOS = 1 WHERE CODFUN = 2;
UPDATE cadfun SET FILHOS = 3 WHERE CODFUN = 3;
UPDATE cadfun SET FILHOS = 2 WHERE CODFUN = 5;
UPDATE cadfun SET FILHOS = 1 WHERE CODFUN = 9;
UPDATE cadfun SET FILHOS = 4 WHERE CODFUN = 20;
UPDATE cadfun SET FILHOS = 3 WHERE CODFUN = 25;

SELECT CODFUN, NOME, FILHOS FROM cadfun;

SELECT CODFUN, NOME, FILHOS FROM cadfun WHERE FILHOS IS NULL;

SELECT CODFUN, NOME, FILHOS FROM cadfun WHERE NOT FILHOS IS NULL;

SELECT * FROM cadfun WHERE SALARIO BETWEEN 1700 AND 2000;

SELECT * FROM cadfun WHERE SALARIO NOT BETWEEN 1700 AND 2000;

SELECT * FROM cadfun WHERE DEPTO IN ('2', '3');

SELECT * FROM cadfun WHERE DEPTO NOT IN ('2', '3');

SELECT * FROM cadfun WHERE NOME LIKE 'A%';

SELECT * FROM cadfun WHERE NOME LIKE '_A%';

SELECT * FROM cadfun WHERE NOME LIKE '%AN%';

SELECT * FROM cadfun WHERE SALARIO LIKE '%6';

SELECT * FROM cadfun WHERE SALARIO LIKE '_5%2';

SELECT * FROM cadfun WHERE NOME NOT LIKE '%AN%';
