USE virtual;

CREATE INDEX indice1 ON cadfun (NOME);

ALTER TABLE cadfun ADD CPF CHAR(11);

SELECT * FROM cadfun; 

CREATE UNIQUE INDEX indice2 ON cadfun (CPF);

UPDATE cadfun SET CPF = '10020011199' WHERE CODFUN = 1;
UPDATE cadfun SET CPF = '10020022299' WHERE CODFUN = 6;
UPDATE cadfun SET CPF = '10020033399' WHERE CODFUN = 8;
UPDATE cadfun SET CPF = '10020044499' WHERE CODFUN = 10;
UPDATE cadfun SET CPF = '10020055599' WHERE CODFUN = 11;
UPDATE cadfun SET CPF = '10020066699' WHERE CODFUN = 12;
UPDATE cadfun SET CPF = '10020077799' WHERE CODFUN = 20;
UPDATE cadfun SET CPF = '10020088899' WHERE CODFUN = 21;
UPDATE cadfun SET CPF = '10022211199' WHERE CODFUN = 22;
UPDATE cadfun SET CPF = '10022233399' WHERE CODFUN = 24;

SELECT * FROM cadfun; 

INSERT INTO cadfun VALUES (
  24,
  'MARCOS INACIO',
  '2',
  'GERENTE',
  2184.33,
  '2006-09-25',
  2,
  '11122233344'
);

INSERT INTO cadfun VALUES (
  50,
  'MARCOS INACIO',
  '2',
  'GERENTE',
  2184.33,
  '2006-09-25',
  2,
  '11122233344'
);

INSERT INTO cadfun VALUES (
  55,
  'MARIA JOSE',
  '3',
  'GERENTE',
  2184.33,
  '2006-10-25',
  2,
  '11122233344'
);

CREATE INDEX indice3 ON cadfun (DEPTO, FUNCAO);

DROP INDEX indice3 ON cadfun;

ALTER TABLE morto ADD CPF CHAR(11);

SELECT * FROM cadfun; 

SELECT * FROM morto;

USE virtual;

GRANT ALL PRIVILEGES ON *.* TO usuario1@localhost 
  IDENTIFIED BY 'abc123' WITH GRANT OPTION
;
GRANT ALL PRIVILEGES ON *.* TO usuario2@'%'
  IDENTIFIED BY 'abc123' WITH GRANT OPTION
;
GRANT SELECT (NOME, SALARIO) ON virtual.cadfun
  TO usuario3@localhost IDENTIFIED BY 'abc123'
;
GRANT UPDATE, INSERT ON virtual.* 
  TO usuario4@localhost IDENTIFIED BY 'abc123'
;

SELECT USER();

SELECT USER();
USE virtual;
SELECT * FROM cadfun;

SELECT NOME, SALARIO FROM cadfun;

USE morto;

USE virtual; 

REVOKE UPDATE ON virtual.cadfun FROM usuario3@localhost;

GRANT UPDATE, INSERT, SELECT ON virtual.* 
  TO usuario3@localhost IDENTIFIED BY 'abc123'
;

DELETE FROM mysql.user WHERE user='usuario1' AND host='localhost';
FLUSH PRIVILEGES;

DELETE FROM mysql.user WHERE user='usuario2' AND host='localhost';
FLUSH PRIVILEGES;

UPDATE mysql.user SET PASSWORD = PASSWORD('123456') 
  WHERE user='usuario3'
;
FLUSH PRIVILEGES;

SHOW GRANTS FOR root@localhost;

CREATE DATABASE IF NOT EXISTS escola;
USE escola;

CREATE TABLE cadpro (
  CODPROP INTEGER(3)  UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOMEPRO VARCHAR(40) NOT NULL,
  CPF     CHAR(11)    NOT NULL UNIQUE
);

CREATE TABLE caddis (
  CODDIS  CHAR(6)     NOT NULL,
  NOMEDIS VARCHAR(40) NOT NULL,
  CODPROF INTEGER(3)  UNSIGNED NOT NULL 
);

ALTER TABLE caddis ADD CONSTRAINT fkCODPRO FOREIGN KEY (CODPROF)
  REFERENCES cadpro (CODPROP)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;

INSERT INTO cadpro VALUES (
  100,
  'SILVANA SOUZA',
  '11122233399'
);

INSERT INTO cadpro VALUES (
  110,
  'JOSE PAULO SILVA',
  '11122244488'
);

INSERT INTO cadpro VALUES (
  120,
  'RENATO DE ABREU',
  '11122244477'
);

INSERT INTO cadpro VALUES (
  130,
  'PENELOPE DA SILVA',
  '11122255566'
);

INSERT INTO cadpro VALUES (
  140,
  'JULIANA DE ALBUQUERQUE',
  '11122266655'
);

INSERT INTO cadpro VALUES (
  150,
  'CARLOS MUNHOZ DA SILVA',
  '11122277744'
);

INSERT INTO caddis VALUES (
  'CG-100',
  'MATEMATICA',
  100
);

INSERT INTO caddis VALUES (
  'CG-110',
  'FISICA',
  100
);

INSERT INTO caddis VALUES (
  'CG-200',
  'PORTUGUES',
  110
);

INSERT INTO caddis VALUES (
  'CG-300',
  'FILOSOFIA',
  110
);

INSERT INTO caddis VALUES (
  'TI-100',
  'ALGORITMOS',
  120
);

INSERT INTO caddis VALUES (
  'TI-200',
  'LINGUAGEM DE PROGRAMACAO I',
  120
);

INSERT INTO caddis VALUES (
  'TI-205',
  'LINGUAGEM DE PROGRAMACAO II',
  130
);

INSERT INTO caddis VALUES (
  'TI-300',
  'BANCO DE DADOS',
  130
);

INSERT INTO caddis VALUES (
  'TI-400',
  'SISTEMAS OPERACIONAIS',
  140
);

INSERT INTO caddis VALUES (
  'TI-500',
  'PROGRAMAÇÃO WEB',
  140
);

INSERT INTO caddis VALUES (
  'CG-100',
  'MATEMATICA',
  150
);

INSERT INTO caddis VALUES (
  'CG-300',
  'FILOSOFIA',
  150
);

SELECT * FROM caddis; 

SELECT * FROM cadpro; 

DELETE FROM cadpro WHERE CODPROP = 100;

DELETE FROM caddis WHERE CODPROF = 100;
SELECT * FROM caddis;

DELETE FROM cadpro WHERE CODPROP = 100;
SELECT * FROM cadpro;

INSERT INTO cadpro VALUES (
  150,
  'JOSE PAULO DE ALMEIDA',
  '11155566655'
);

INSERT INTO cadpro VALUES (
  300,
  'MARIANA DOS SANTOS SILVA',
  '11122277744'
);

SELECT caddis.CODDIS, caddis.NOMEDIS, cadpro.NOMEPRO 
  FROM caddis, cadpro 
  WHERE caddis.CODPROF = cadpro.CODPROP
;

SHOW INDEX FROM caddis;

SHOW INDEX FROM caddis;
